services:
  - type: web
    name: campus-reservation
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn moniterselection.wsgi:application  
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,127.0.0.1,localhost
      - key: DATABASE_URL
        fromDatabase:
          name: reservation-db
          property: connectionString
    plan: free

databases:
  - name: reservation-db
    databaseName: reservation
    user: admin
    plan: free
